---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: exorcism-webhook
  namespace: default
spec:
  isCA: true
  secretName: admission-tls
  commonName: exorcism.default.svc.cluster.local
  issuerRef:
    name: selfsigned
  dnsNames:
  - "exorcism"
  - "exorcism.default"
  - "exorcism.default.svc"
